### ISSUE TITLE
type-graphql missing in blog

### ISSUE THREAD

**Issue by bm-stschneider** [TannerGabriel/Blog#33]
It would be nice if you can update the tutorial to actually match the files provided, missing @ObjectType for example will eventually make the nestjs app to never work correctly.

**Comment by TannerGabriel** [comment]
> It would be nice if you can update the tutorial to actually match the files provided, missing @ObjectType for example will eventually make the nestjs app to never work correctly.

I don't fully understand what you are trying to say but look over my nest-graphql sample nonetheless and found some little issues and fixed them. Now the question remains where exactly you think that the @ObjectType decorator is missing because I didn't see it?

Thank you for your help and all the best.

**Comment by bm-stschneider** [comment]
oh boy, where to start. ok the dto file is incomplete. because as soon as you try to use graphql it will throw because it can't generate a schema.
You import a inpu-items without mentioning the content of that file.

**Comment by TannerGabriel** [comment]
I think we are not on the same page when talking about this issue. I personally don't see a problem with the DTO file of the nest-graphql sample. That is why I would recommend you do submit a pull request to this repository with your recommended changes.

Thank you for your effort and all the best.

**Comment by bm-stschneider** [comment]
I wasn't talking about the repo, I was talking about https://gabrieltanner.org/blog/nestjs-graphqlserver the article

**Comment by TannerGabriel** [comment]
Ok, now I get it. Thank you very much for the feedback I will fix this issue ASAP.
