### ISSUE TITLE
Your article doesn't explain what diskStorage is

### ISSUE THREAD

**Issue by nquinn721** [TannerGabriel/Blog#54]
I like your article you made about this topic, however, one of my biggest pet peeves is someone explaining something but has code in their article and they don't at least show what import it comes from. How can anyone follow your article if they don't know what `diskStorage` is without coming to the github and looking into it themselves?

**Comment by TannerGabriel** [comment]
Thank you for telling me your concerns about the explanation in my article. I will take a look at it and see what I can do.
