### ISSUE TITLE
Missing extends in items.interface.ts in Blog/Nest-CRUD

### ISSUE THREAD

**Issue by eddiemuss** [TannerGabriel/Blog#93]
I think you missed to extends `Document` in [item.interface.ts](https://github.com/TannerGabriel/Blog/blob/master/Nest-CRUD/src/items/interfaces/item.interface.ts) you did it in your article about graphQL.

To better describe my problem: By following the instruction on [crash course nest](https://medium.com/free-code-camp/a-crash-course-in-typescript-e6bf9c10946) I get the type errors that in `items.service.ts` `save` is not defined with I think is related that the Type `Item` doesn't contain all the logic from mongoose.

Both Blog posts are well written. It's fun to follow them and to get a first view into Nest.

**Comment by TannerGabriel** [comment]
Great to hear that you enjoyed the articles, and thank you for the feedback. I will take a look at the file and fix it if needed!
